config/routes.rb
Rails.application.routes.draw do
  # get 'comments/create'
  devise_for :users
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :blog_posts
  root "blog_posts#index"

  resources :users do
    resources :blog_posts
  end
  post '/blog_posts/:id/comments', to: 'comments#create', as: :comments
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
  has_one_attached :image
  belongs_to :user
  has_many :comments

  def self.filter_on_constraints(constraint_hash)
    records = BlogPost.all
    operator_hash = {
        :location => '==',
        :category => '==',
    }
    constraint_hash.each_pair do |key, value|
      symbol = key.to_sym
      operator = operator_hash[symbol]
      if !operator.nil?
        if !value.to_s.empty?
          records = records.where("#{symbol.to_s} #{operator} ?", value)
        end
      end
    end
    records
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :blog_post
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :blog_posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController

  before_action :authenticate_user!, :only=>[:edit, :update, :new, :create, :destroy]

  def index
    @posts = BlogPost.all
    @user = current_user
    if params[:filters]
      session[:filters] = params[:filters]
      # redirect_to rental_properties_path(params[:filters])
      @posts = @posts.filter_on_constraints(params[:filters])
      # session[:filters] = params[:filters]
    elsif session[:filters]
      params[:filters] = session[:filters]
      # redirect_to rental_properties_path(params[:filters])
      @posts = @posts.filter_on_constraints(session[:filters])
      # session.clear
    end
  end

  def show
    @post = BlogPost.find(params[:id])
    @user = @post.user.email
    @comments = @post.comments
  end

  def edit
    @post = BlogPost.find(params[:id])
    @user_id = current_user.id
  end

  def new
    @post = BlogPost.new
    @user_id = current_user.id
  end

  def update
    @post = BlogPost.find params[:id]
    if (@post.user == current_user)
      @post.update(create_update_params)
      if @post.save
        flash[:notice] = "#{@post.title} was successfully updated!"
        redirect_to blog_post_path(@post) and return
      end
    else
      flash[:warning] = "You don't have permission to do that."
      redirect_to edit_blog_post_path(@post) and return
    end
  end

  def destroy
    @post = BlogPost.find(params[:id])
    if (@post.user == current_user)
      @post.destroy
      flash[:notice] = "Blog Post '#{@post.title}' deleted!"
      redirect_to blog_posts_path()
    else
      flash[:warning] = "You don't have permission to do that."
      redirect_to blog_post_path and return
    end
  end

  def create
    @post = BlogPost.new(create_update_params)
    @post.user_id = current_user.id if current_user

    if !@post.location?
      flash[:warning] = "No Location Provided - Failed to Create Blog Post."
      redirect_to(new_blog_post_path()) and return
    elsif !@post.title?
      flash[:warning] = "No Title Provided - Failed to Create Blog Post."
      redirect_to(new_blog_post_path()) and return
    elsif !@post.rating? && !(@post.rating == 0)
      flash[:warning] = "No Rating Provided - Failed to Create Blog Post."
      redirect_to(new_blog_post_path()) and return
    elsif !@post.category?
      flash[:warning] = "No Meal Time Provided - Failed to Create Blog Post."
      redirect_to(new_blog_post_path()) and return
    elsif @post.save
      flash[:notice] = "Blog Post #{@post.title} created!"
      redirect_to(blog_posts_path()) and return
    else
      flash[:warning] = "Unknown Error"
      redirect_to(new_blog_post_path()) and return
    end
  end

private
  def create_update_params
    params.require(:blog_post).permit(:title, :description, :location, :category, :rating, :image, :current_user)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = BlogPost.find(params[:id])
    # if @post.nil?
    #   redirect_to blog_posts_path
    # else
    @comment = Comment.new(create_comment_params)
    @comment.user = current_user
    @post.comments << @comment
    comment = Comment.new(create_comment_params)
    comment.user = current_user
    
    # redirect_to blog_post_path(@post)
    # byebug
    # if @comment == ''
    #   redirect_to blog_post_path(@post)
    
    if @comment.save
      # byebug
      render :partial => comment
      # redirect_to blog_post_url(@post)
    end
      # redirect_to blog_post_path(@post)
    # else
    #   redirect_to blog_post_path(@post)
    # end
    
  end

private
  def create_comment_params
    params.require(:comment).permit(:comment)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_posts_helper.rb
module BlogPostsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/blog_posts/edit.html.haml
%h2.editpage_title Edit Blog Post
.h5
    #myBar.progress-bar
-# .progress-container


%p.navbar-text.pull-right
- if user_signed_in?
    %p.identity= "Logged in as " + current_user.email + "."
    %p.navbar-link_up= link_to 'Edit profile', edit_user_registration_path
    %p.navbar-link_in= link_to "Logout", destroy_user_session_path, method: :delete
- else
    %p.navbar-link_up= link_to "Sign up", new_user_registration_path
    %p.navbar-link_in= link_to "Login", new_user_session_path

= form_for @post, :method => :put do |post|
    - if flash[:notice]
        .col-md-offset-2
        #notice.message
            %span= flash[:notice]
        .row
    - if flash[:warning]
        .col-md-offset-2
        #notice.message_warning
            %span= flash[:warning]
        .row
    
    -# %p.curr_img= post.image.variant(resize: "500x500^") 
    %div.edit_text
        = post.label :title, 'Title', :class => 'edit_title'
        .row
        = post.text_field :title, :class => 'edit_title2'
        .row
        = post.label :category, 'Meal Time', :class => 'edit_cat'
        .row
        = post.select :category, ['Breakfast', 'Lunch', 'Dinner'], prompt: 'Select One', :class => 'edit_cat2'
        .row
        = post.label :location, 'Location', :class => 'edit_loc'
        .row
        = post.select :location, ['Frank', 'Coop', 'Library Cafe'], prompt: 'Select One', :class => 'edit_loc2'
        .row
        = post.label :description, 'How was it?', :class => 'edit_desc'
        .row
        = post.text_field :description, :class => 'edit_desc2'
        .row
        = post.label :rating, 'Rating', :class => 'edit_rate'
        .row
        = post.number_field :rating, in: 0..5, step: 1, :class => 'edit_rate2'
        .row
        =post.label :image, "Image",:class => 'edit_img'
        .row
        =post.file_field :image, accept: "image/png,image/gif,image/jpeg", :class => 'edit_img2'
        .row
        %br
        = post.submit "Update Blog Post", :class => 'edit_submit'
        .row
        .row
        = link_to "Back To All Blog Posts", blog_posts_path(), :class => 'edit_back'

app/views/blog_posts/index.html.haml
-# %script{:src => "https://code.jquery.com/jquery-3.4.0.min.js", :type => "text/javascript"}
%script{:src => "//ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js"}

#main.container
  %div.linkbox
    %p.moodle= link_to "Moodle", "https://moodle.colgate.edu/login/index.php", target: :_blank
    %p.portal= link_to "Portal", "https://portal.colgate.edu/uPortal/f/welcome/normal/render.uP", target: :_blank
    %p.library= link_to "Library", "https://cul.colgate.edu/", target: :_blank
    %p.news= link_to "News", "https://news.colgate.edu/", target: :_blank

  .h5
    .progress-container
      #myBar.progress-bar
  -# %script{:src => "CURTISSEFRANKDININGHALLFOODBLOG/app/assets/javascripts/blog_posts.js"}
  - if flash[:notice]
    .col-md-offset-2
    #notice.message
      %span= flash[:notice]
    .row

  - if flash[:warning]
    .col-md-offset-2
    #notice.message_warning
      %span= flash[:warning]
    .row

  %h1.header To Be Frank Food Blog

  %button.new{:id => "newbutton"}= link_to "New Post", new_blog_post_path()
  -# %p.new= link_to "Create A New Blog Post", new_blog_post_path()

  %p.scrollToTop{:href => "#"}
    %i.fa.fa-angle-up
    Back to top

  %p.navbar-text.pull-right
    - if user_signed_in?
      %p.identity= "Logged in as " + current_user.email + "."
      %p.navbar-link_up= link_to 'Edit profile', edit_user_registration_path
      %p.navbar-link_in= link_to "Logout", destroy_user_session_path, method: :delete
    - else
      %t9.body
        .navbar-link_up= link_to "Sign up", new_user_registration_path
        .navbar-link_in= link_to "Login", new_user_session_path



  .row
  %p.filter
    =form_for :filters, :method => :get do |p|
      %div.filterout
        =p.label :location, "Location", :class => 'loc'
        =p.select :location, ['Frank', 'Coop', 'Library Cafe'], prompt: 'Select One', :class => 'loc2'
        -# %br
        =p.label :category, "Meal Time", class: 'cat'
        =p.select :category, ['Breakfast', 'Lunch', 'Dinner'], prompt: 'Select One', class: 'cat2'
        -# %br
        =submit_tag "Refine the list of blog posts", :class => 'submit_filter'
        %td.row=link_to 'Clear filters', session.clear, :class => 'clear_filter'
    .row

  %table.table
    %thead
      %tr
        %th
        -# %th Title
        -# %th Category
        -# %th Location
        -# %th Description
        -# %th Rating
    %tbody
      -@posts.each do |post|
        %p.post
          %p.image= link_to image_tag(post.image.attached? ? post.image.variant(resize: "400x400^") : 'noimg.png'), blog_post_path(post), :id => "#{post.title}"
          .title= "#{post.title}"
          .category= "#{post.category}"
          .location= "#{post.location}"
          .cat_loc= "#{post.category} @ #{post.location}"
          .description= "#{truncate(post.description, length: 30)}"
          .rating= "#{post.rating}" + "/5 Stars"

    

app/views/blog_posts/new.html.haml
- if flash[:notice]
    .col-md-offset-2
    #notice.message
        %span= flash[:notice]
    .row
- if flash[:warning]
    .col-md-offset-2
    #notice.message_warning
        %span= flash[:warning]
    .row

%h2.create_head Create A New Blog Post

%p.navbar-text.pull-right
    - if user_signed_in?
        %p.identity= "Logged in as " + current_user.email + "."
        %p.navbar-link_up= link_to 'Edit profile', edit_user_registration_path
        %p.navbar-link_in= link_to "Logout", destroy_user_session_path, method: :delete
    - else
        %p.navbar-link_up= link_to "Sign up", new_user_registration_path
        %p.navbar-link_in= link_to "Login", new_user_session_path

%t2.body
    %span
    = form_for @post, :method => :post do |post|
        = post.label :title, 'Title', :class => 'title1'
        .row
        = post.text_field :title, :class => 'title2'
        .row
        = post.label :category, 'Meal Time', :class => 'cat1'
        .row
        = post.select :category, ['Breakfast', 'Lunch', 'Dinner'], prompt: 'Select One', :class => 'cat2'
        .row
        = post.label :location, 'Location', :class => 'loc1'
        .row
        = post.select :location, ['Frank', 'Coop', 'Library Cafe'], prompt: 'Select One', :class => 'loc2'
        .row
        = post.label :description, 'How was it?', :class => 'desc1'
        .row
        = post.text_field :description, :class => 'desc2'
        .row
        = post.label :rating, 'Rating', :class => 'rate1'
        .row
        = post.number_field :rating, in: 0..5, step: 1, :class => 'rate2'
        .row
        =post.label :image, "Image", :class => 'img1'
        .row
        =post.file_field :image, accept: "image/png,image/gif,image/jpeg", :class => 'img2'
        .row
        = submit_tag "Create A New Blog Post", :class => 'submit'
        .row
        .row
        = link_to "Back To All Blog Posts", blog_posts_path(), :class => 'back'

app/views/blog_posts/show.html.haml
#main.container
    .h5
        -# .progress-container
        #myBar.progress-bar
    %h1.header{:id => "headertitle"}= "To Be Frank Food Blog"


    %p.scrollToTop{:href => "#"}
        %i.fa.fa-angle-up
        Back to top

    %p.navbar-text.pull-right
    - if user_signed_in?
        %p.identity= "Logged in as " + current_user.email + "."
        %p.navbar-link_up= link_to 'Edit profile', edit_user_registration_path
        %p.navbar-link_in= link_to "Logout", destroy_user_session_path, method: :delete
    - else
        %p.navbar-link_up= link_to "Sign up", new_user_registration_path
        %p.navbar-link_in= link_to "Login", new_user_session_path


    - if flash[:notice]
        .col-md-offset-2
        #notice.message
            %span= flash[:notice]
        .row
    - if flash[:warning]
        .col-md-offset-2
        #notice.message_warning
            %span= flash[:warning]
        .row


    .row
        .col-md-offset-1
        .col-md-4
            %h3.header.title= "#{@post.title}"
            %h4.header.title= "By #{@user}"
            %p= render_shareable
    %div.show_imgandtext
        
        %div.show_detailtext
            %p.title_show= "#{@post.title}" 
            %p.image_show= image_tag @post.image.attached? ? @post.image.variant(resize: "500x500^") : 'noimg.png'
            %p.location_show= "#{@post.category} at #{@post.location}"
            %p.description_show= "#{@post.description}"
            %p.rating_show= "Rated #{@post.rating}/5 Stars"

    %br
    %br

%br
%br
#comments.row
    %h3 Comments
    %ul
    %div.commentstext
        -@comments.each do |comment|
            =render :partial => comment

.row
    -if user_signed_in?
        =form_with(id: :comment_form, model: Comment.new, url: comments_path(@post), data: { type: :html } ) do |f|
            =f.label :comment
            =f.text_area :comment, :id => "commentbox"
            =f.submit "Add comment", :id => "submitcomment"
    -else
        %p Sign in to post a comment.
%br


    .row
        .col-md-offset-1
        %div.crudlinks
            .editlink= link_to('Edit', edit_blog_post_path(@post))
            .deletelink= link_to('Delete', blog_post_path(@post), :method => :delete)
            .backlink= link_to('Back', blog_posts_path)

app/views/comments/_comment.html.haml
%li= "#{comment.comment} (by #{comment.user.email} @ #{comment.updated_at})"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application'%>
    <%= javascript_include_tag 'application'%>
  </head>

  <body>
    <%= yield %>
  </body>
</html>